module.exports = {
    ON_CARD_PLACEMENT_CHANGE: "ON_CARD_PLACEMENT_CHANGE",
    SEGMENT_ADDED: "SEGMENT_ADDED",
    CARD_ADDED: "CARD_ADDED",
    ON_SECTION_PLACEMENT_CHANGE: "ON_SECTION_PLACEMENT_CHANGE",

  };